### ISSUE TITLE
update configparser to work with python 3.12+

### ISSUE THREAD

**Issue by psferguson** [DarkEnergySurvey/ugali#105]
in python 3.2 SafeConfigParser was depreciated (and the readfp method) and removed in 3.12
the current versioneer.py uses these
https://github.com/DarkEnergySurvey/ugali/blob/fa5ea4f06f69b4a5043f6ddd838ee7c0779af809/versioneer.py#L412-L414

The fix is to replace with ConfigParser() and the read_file method

```
parser = configparser.ConfigParser()
    with open(setup_cfg, "r") as f:
        parser.read_file(f)
```

I have confirmed that I can successfully install and run with this change.
Happy to make a PR if I am given permission to

**Comment by kadrlica** [comment]
Thanks @psferguson! It'd be great to have a PR for this. I've added you to the collaborator list, but we usually do most of our PRs by forking.

**Comment by willcerny** [comment]
I've created PR #106 to implement Peter's fix
