### ISSUE TITLE
Isochrones updates and distribution

### ISSUE THREAD

**Issue by kadrlica** [DarkEnergySurvey/ugali#21]
This is a moving target since new isochrones come out all the time. It's also a pain because of the way we distribute the isochrone files. We might want to think about a standalone isochrone package (certainly a lot of work to be done there). We might also want to think about a deeper integration of the code to download isochrones from the web.

**Comment by bechtol** [comment]
Given that the theoretical isochrones (so far) do not exactly match the RGB, we might consider implementing an empirical isochrone motivated by the photometry of confirmed member stars in dSphs, or based on globular cluster ridgelines.

**Comment by kadrlica** [comment]
Good point. We have a few empirical isochrones implemented in development versions of the code. We would need to roll a new isochrone tarball to distribute them more broadly.

**Comment by sazabi4** [comment]
regarding downloading the isochrone from web and built that in the code, I want to point out that Sergey has code doing that and it is available in the LSST hack project:

https://github.com/LSSTDESC/LSSTDarkMatter/tree/master/satellites

see down_girardi.py and read_girardi.py where he uses BeautifulSoup to download isochrone while running python.

As for the empirical isochrone, I think both using confirmed dwarf member and the globular cluster is a good idea. 

One thing we never understand is that Josh claim for SDSS dwarfs, the confirmed member is always on the top of the M92 isochrone, while for DEs dwarfs, it tends to be between the M92 and PARSEC isochrone. I think we should look into this,  and also get the confirmed members in SDSS dwarfs with SDSS photometry.

**Comment by kadrlica** [comment]
We already have very similar code here:
https://github.com/DarkEnergySurvey/ugali/blob/master/ugali/preprocess/padova.py

Also code for dotter isochrones here:
https://github.com/DarkEnergySurvey/ugali/blob/master/ugali/preprocess/dotter.py
