### ISSUE TITLE
Generalized bands in plot output

### ISSUE THREAD

**Issue by sidneymau** [DarkEnergySurvey/ugali#53]
Generalize bands in plot output, i.e.
https://github.com/DarkEnergySurvey/ugali/blob/9deabbc6157a622853e835e882c9bf1c4899f967/ugali/utils/plotting.py#L837-L838

Examples:

Pythonic style string formatting
```
plt.xlabel(r'${} - {}$'.format(self.isochrone.band_1, self.isochrone.band_2)
plt.ylabel(r'${}$'.format(self.isochrone.band_1))
```

C style string formatting
```
plt.xlabel(r'$%s - %s$' % (self.isochrone.band_1, self.isochrone.band_2))
plt.ylabel(r'$%s$' % self.isochrone.band_1)
```

**Comment by kadrlica** [comment]
Thanks @smau this looks good. How do you feel about submitting a pull request?

**Comment by sidneymau** [comment]
Sounds good... let me update my ugali branch and then make the changes
