### ISSUE TITLE
Fix string type check for py2/py3

### ISSUE THREAD

**Issue by kadrlica** [DarkEnergySurvey/ugali#62]
We need a more robust way to check for strings. I think that putting an `isstr` function in `utils.fileio.py` like suggested in [this answer](https://stackoverflow.com/a/11301781/4075339) would be a reasonable solution.

**Comment by sidneymau** [comment]
This is relevant here: https://github.com/DarkEnergySurvey/ugali/blob/master/ugali/analysis/source.py#L100

where I needed to change `if isinstance(srcmdl,str):` to `if isinstance(srcmdl,(basestring,str,unicode)):` since the srcmdl was `u'./mcmc/juicy_i_mcmc.yaml'` (a unicode string)

**Comment by kadrlica** [comment]
Closed by #63
