### ISSUE TITLE
ugali.stats.peak_interval appears to be calculating the interval incorrectly 

### ISSUE THREAD

**Issue by psferguson** [DarkEnergySurvey/ugali#80]
We are sometimes seeing that the peak interval does not contain the peak (kde peak) 
I think this has to do with lines 99 and 100, which currently read: 
`lo = x[min_idx]`
`hi = x[min_idx+window]`

and should probably be changed to something along the lines of 
`lo = starts[select][min_idx]`
`hi = ends[select][min_idx]`

**Comment by kadrlica** [comment]
Yeah, this looks right to me. Linking the offending lines here:
https://github.com/DarkEnergySurvey/ugali/blob/00b30c5ac84e4cada338fb77d33aa31afabca7bb/ugali/utils/stats.py#L93-L100

**Comment by kadrlica** [comment]
@psferguson would you be able to make a PR for this? Maybe we also need a test?

**Comment by kadrlica** [comment]
I think things should be fixed. I've also added some tests. Here's a look at how the different intervals compare to each other.

![image](https://user-images.githubusercontent.com/5605123/125175921-12664100-e195-11eb-9997-9804b0f88cd1.png)
